import React, { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextType {
  t: (key: string) => string;
  isAdmin: boolean;
  setIsAdmin: (isAdmin: boolean) => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  tr: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.treatments': 'Treatments',
    'nav.destinations': 'Destinations',
    'nav.contact': 'Contact',
    'nav.support': 'Support',
    'nav.blog': 'Blog',
    'nav.faq': 'Faq',
    'nav.allTreatments': 'All Treatments',
    'nav.findClinics': 'Find Clinics',
    'nav.signIn': 'SignIn',
    'nav.signUp': 'signUp',
    'nav.signOut': 'signOut',
    'nav.dashboard': 'Dashboard',
    
    // Search
    'search.placeholder': 'Tedavi, klinik, doktor ara...',
    'search.button': 'Ara',
    'search.noResults': 'Sonuç bulunamadı',
    'search.allDestinations': 'Tüm Destinasyonlar',
    
    // Treatments
    'treatment.hairTransplant': 'Saç Ekimi',
    'treatment.dental': 'Diş Tedavileri',
    'treatment.plasticSurgery': 'Plastik Cerrahi',
    'treatment.eyeSurgery': 'Göz Ameliyatı',
    'treatment.fertility': 'Tüp Bebek',
    'treatment.cardiology': 'Kalp Cerrahisi',
    'treatment.orthopedic': 'Ortopedi',
    
    // Pages
    'pages.howItWorks': 'Nasıl Çalışır',
    'pages.support': 'Destek',
    'pages.reviews': 'Yorumlar',
    'pages.travelGuides': 'Seyahat Rehberleri',
    'pages.insurance': 'Sigorta Yardımı',
    'pages.clinicSignup': 'Klinik Kaydı',
    'pages.marketing': 'Pazarlama Araçları',
    'pages.successStories': 'Başarı Hikayeleri',
    'pages.pricing': 'Fiyatlandırma',
    'pages.apiDocs': 'API Dokümantasyonu',
    
    // Language & Settings
    'language.title': 'Dil Ayarları',
    'language.select': 'Dil Seçin',
    'language.current': 'Mevcut Dil',
    'language.turkish': 'Türkçe',
    'language.english': 'İngilizce',
    'language.save': 'Kaydet',
    'language.cancel': 'İptal',
    'language.success': 'Dil başarıyla değiştirildi',
    'language.systemLanguage': 'Sistem Dili',
    'language.userLanguage': 'Kullanıcı Dili',
    'language.adminControl': 'Admin Dil Kontrolü',
    'language.changeSystemLanguage': 'Sistem Dilini Değiştir',
    
    // Admin Dashboard
    'admin.dashboard': 'Yönetici Paneli',
    'admin.welcome': 'Hoş geldiniz',
    'admin.totalClinics': 'Toplam Klinik',
    'admin.totalPatients': 'Toplam Hasta',
    'admin.monthlyRevenue': 'Aylık Gelir',
    'admin.pendingApprovals': 'Bekleyen Onaylar',
    'admin.overview': 'Genel Bakış',
    'admin.clinics': 'Klinikler',
    'admin.patients': 'Hastalar',
    'admin.transactions': 'İşlemler',
    'admin.reports': 'Raporlar',
    'admin.settings': 'Ayarlar',
    'admin.approvals': 'Onaylar',
    'admin.recentClinics': 'Son Eklenen Klinikler',
    'admin.recentBookings': 'Son Rezervasyonlar',
    'admin.noDataAvailable': 'Veri mevcut değil',
    'admin.viewDetails': 'Detayları Görüntüle',
    'admin.approve': 'Onayla',
    'admin.reject': 'Reddet',
    'admin.messaging': 'Mesajlaşma',
    'admin.crm': 'Müşteri Yönetimi',
    'admin.campaigns': 'Kampanyalar',
    'admin.notifications': 'Bildirimler',
    'admin.integrations': 'Entegrasyonlar',
    'admin.security': 'Güvenlik',
    'admin.activity': 'Aktivite',
    'admin.cms': 'İçerik Yönetimi',
    'admin.languageSettings': 'Dil Ayarları',
    
    // Document Review
    'document.approve': 'Belgeyi Onayla',
    'document.reject': 'Belgeyi Reddet',
    'document.view': 'Belgeyi Görüntüle',
    'document.download': 'İndir',
    'document.details': 'Dosya Detayları',
    'document.fileName': 'Dosya Adı',
    'document.fileSize': 'Dosya Boyutu',
    'document.uploadDate': 'Yükleme Tarihi',
    'document.clinicInfo': 'Klinik Bilgisi',
    'document.documentInfo': 'Belge Bilgileri',
    'document.documentType': 'Belge Türü',
    'document.type': 'Türü',
    'document.verificationStatus': 'Doğrulama Durumu',
    'document.clinic': 'Klinik',
    'document.location': 'Konum',
    'document.openDocument': 'Belgeyi Aç',
    'document.approved': 'Belge Onaylandı',
    'document.rejected': 'Belge Reddedildi',
    'document.pending': 'Onay Bekliyor',
    'document.confirmApproval': 'belgesini onaylamak istediğinizden emin misiniz?',
    'document.confirmRejection': 'belgesini reddetmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
    'document.approvalNotes': 'İnceleme notları (opsiyonel)',
    'document.rejectionReason': 'Ret sebebi (önerilen)',
    'document.confirmApprovalAction': 'Onayı Doğrula',
    'document.confirmRejectionAction': 'Reddi Doğrula',
    'document.approving': 'Onaylanıyor...',
    'document.rejecting': 'Reddediliyor...',
    
    // Treatment Approval
    'treatment.approve': 'Tedaviyi Onayla',
    'treatment.reject': 'Tedaviyi Reddet',
    'treatment.viewDetails': 'Detayları Görüntüle',
    'treatment.approved': 'Tedavi Onaylandı',
    'treatment.rejected': 'Tedavi Reddedildi',
    'treatment.confirmApproval': 'tedavisini onaylamak istediğinizden emin misiniz? Hastalara görünür hale gelacektir.',
    'treatment.confirmRejection': 'tedavisini reddetme sebebinizi belirtin:',
    'treatment.approvalNotes': 'Onaylama notları (opsiyonel)',
    'treatment.rejectionReason': 'Ret sebebi (gerekli)',
    
    // Messaging
    'messaging.conversations': 'Konuşmalar',
    'messaging.newMessage': 'Yeni Mesaj',
    'messaging.typeMessage': 'Mesajınızı yazın...',
    'messaging.send': 'Gönder',
    'messaging.searchConversations': 'Konuşmalarda ara...',
    'messaging.noConversations': 'Henüz konuşma yok',
    'messaging.selectConversation': 'Bir konuşma seçin',
    'messaging.attachFile': 'Dosya Ekle',
    'messaging.attachImage': 'Resim Ekle',
    'messaging.priority': 'Öncelik',
    'messaging.status': 'Durum',
    'messaging.tags': 'Etiketler',
    'messaging.filters': 'Filtreler',
    'messaging.clearFilters': 'Filtreleri Temizle',
    'messaging.assignTo': 'Atanan Kişi',
    'messaging.unassigned': 'Atanmamış',
    'messaging.markAsRead': 'Okundu Olarak İşaretle',
    'messaging.markAsUnread': 'Okunmadı Olarak İşaretle',
    'messaging.archive': 'Arşivle',
    'messaging.delete': 'Sil',
    'messaging.typing': 'yazıyor...',
    'messaging.justNow': 'Az önce',
    'messaging.hoursAgo': 'saat önce',
    'messaging.daysAgo': 'gün önce',
    'messaging.download': 'İndir',
    'messaging.fileSize': 'Dosya Boyutu',
    'messaging.filtersActive': 'Filtreler aktif',
    
    // Priorities
    'priority.low': 'Düşük',
    'priority.normal': 'Normal',
    'priority.high': 'Yüksek',
    'priority.urgent': 'Acil',
    
    // Status
    'status.pending': 'Beklemede',
    'status.approved': 'Onaylandı',
    'status.active': 'Aktif',
    'status.completed': 'Tamamlandı',
    'status.resolved': 'Çözüldü',
    'status.closed': 'Kapalı',
    'status.all': 'Tümü',
    
    // Common
    'common.loading': 'Yükleniyor...',
    'common.save': 'Kaydet',
    'common.cancel': 'İptal',
    'common.delete': 'Sil',
    'common.edit': 'Düzenle',
    'common.view': 'Görüntüle',
    'common.close': 'Kapat',
    'common.next': 'İleri',
    'common.previous': 'Geri',
    'common.submit': 'Gönder',
    'common.confirm': 'Onayla',
    'common.error': 'Hata',
    'common.success': 'Başarılı',
    'common.search': 'Ara',
    'common.filter': 'Filtre',
    'common.clear': 'Temizle',
    'common.apply': 'Uygula',
    'common.reset': 'Sıfırla',
    'common.back': 'Geri',
    'common.forward': 'İleri',
    'common.refresh': 'Yenile',
    'common.export': 'Dışa Aktar',
    'common.import': 'İçe Aktar',
    'common.download': 'İndir',
    'common.upload': 'Yükle',
    'common.select': 'Seç',
    'common.selectAll': 'Tümünü Seç',
    'common.deselectAll': 'Seçimi Kaldır',
    'common.add': 'Ekle',
    
    // Footer
    'footer.popularTreatments': 'Popüler Tedaviler',
    'footer.topDestinations': 'Popüler Destinasyonlar',
    'footer.forPatients': 'Hastalar İçin',
    'footer.forClinics': 'Klinikler İçin',
    'footer.trustTitle': 'Neden JAW BREAKER?',
    'footer.trustSubtitle': 'Medikal turizmde güvenilir partneriniz',
    'footer.newsletter': 'Güncel Kalın',
    'footer.newsletterDesc': 'En son fırsatları ve sağlık turizmi rehberlerini e-postanızda alın.',
    'footer.subscribe': 'Abone Ol',
    'footer.privacyPolicy': 'Gizlilik Politikası',
    'footer.termsOfService': 'Kullanım Şartları',
    'footer.cookiePolicy': 'Çerez Politikası',
    'footer.medicalDisclaimer': 'Tıbbi Sorumluluk Reddi',

    // Support page translations
    'support.title': 'Destek Merkezi',
    'support.subtitle': 'Her adımda yanınızdayız',
    'support.phoneSupport': 'Telefon Desteği',
    'support.phoneDescription': 'Tıbbi koordinatörlerimizle doğrudan konuşun',
    'support.emailSupport': 'E-posta Desteği',  
    'support.emailDescription': 'Sorularınıza detaylı yanıtlar alın',
    'support.liveChat': 'Canlı Sohbet',
    'support.chatDescription': 'Destek ekibimizden anında yardım',
    'support.chatWidget': 'Her sayfada sohbet widget\'ı',
    'support.available247': '7/24 Mevcut',
    'support.responseTime': '2 saat içinde yanıt',
    'support.emergencySupport': 'Acil Durum Desteği',
    'support.emergencyDescription': 'Şu anda seyahat halindeyseniz ve acil yardıma ihtiyacınız varsa',
    'support.emergencyAvailability': 'Tıbbi acil durumlar ve acil seyahat yardımı için 7/24 mevcut',
    'support.faqTitle': 'Sıkça Sorulan Sorular',
    'support.faq1Question': 'Nasıl tedavi rezervasyonu yaparım?',
    'support.faq1Answer': 'Basitçe tedavilerimize göz atın, tercih ettiğiniz kliniği seçin ve "Rezervasyon Yap" düğmesine tıklayın. Koordinatörlerimiz süreç boyunca size rehberlik edecek.',
    'support.faq2Question': 'Fiyata neler dahil?',
    'support.faq2Answer': 'Tüm paketler tıbbi ücretler, konaklama, havaalanı transferleri ve özel koordinatör hizmetini içerir. Ek hizmetler açıkça işaretlenmiştir.',
    'support.faq3Question': 'Rezervasyonum korunuyor mu?',
    'support.faq3Answer': 'Evet, tüm rezervasyonlar garantimiz altında korunmaktadır. Tam para iade koruması ve kalite güvencesi sunuyoruz.',
    'support.faq4Question': 'Hangi dillerde destek veriyorsunuz?',
    'support.faq4Answer': 'İngilizce, Türkçe, Rusça, Arapça, Almanca ve Fransızca dillerinde destek sunuyoruz. Kliniklerimiz çok dilli personele sahiptir.',
    'support.officesTitle': 'Ofislerimiz',
    'support.usa': 'Amerika Birleşik Devletleri',
    'support.turkey': 'Türkiye'
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.treatments': 'Treatments',
    'nav.destinations': 'Destinations',
    'nav.contact': 'Contact',
    'nav.support': 'Support',
    'nav.blog': 'Blog',
    'nav.faq': 'FAQ',
    'nav.allTreatments': 'All Treatments',
    'nav.findClinics': 'Find Clinics',
    'nav.signIn': 'Sign In',
    'nav.signUp': 'Sign Up',
    'nav.signOut': 'Sign Out',
    'nav.dashboard': 'Dashboard',
    
    // Search
    'search.placeholder': 'Search treatments, clinics, doctors...',
    'search.button': 'Search',
    'search.noResults': 'No results found',
    'search.allDestinations': 'All Destinations',
    
    // Treatments
    'treatment.hairTransplant': 'Hair Transplant',
    'treatment.dental': 'Dental Treatments',
    'treatment.plasticSurgery': 'Plastic Surgery',
    'treatment.eyeSurgery': 'Eye Surgery',
    'treatment.fertility': 'Fertility Treatments',
    'treatment.cardiology': 'Cardiac Surgery',
    'treatment.orthopedic': 'Orthopedic',
    
    // Pages
    'pages.howItWorks': 'How it Works',
    'pages.support': 'Support',
    'pages.reviews': 'Reviews',
    'pages.travelGuides': 'Travel Guides',
    'pages.insurance': 'Insurance Help',
    'pages.clinicSignup': 'Join as Provider',
    'pages.marketing': 'Marketing Tools',
    'pages.successStories': 'Success Stories',
    'pages.pricing': 'Pricing Plans',
    'pages.apiDocs': 'Integration API',
    
    // Language & Settings
    'language.title': 'Language Settings',
    'language.select': 'Select Language',
    'language.current': 'Current Language',
    'language.turkish': 'Turkish',
    'language.english': 'English',
    'language.save': 'Save',
    'language.cancel': 'Cancel',
    'language.success': 'Language changed successfully',
    'language.systemLanguage': 'System Language',
    'language.userLanguage': 'User Language',
    'language.adminControl': 'Admin Language Control',
    'language.changeSystemLanguage': 'Change System Language',
    
    // Admin Dashboard
    'admin.dashboard': 'Admin Dashboard',
    'admin.welcome': 'Welcome',
    'admin.totalClinics': 'Total Clinics',
    'admin.totalPatients': 'Total Patients',
    'admin.monthlyRevenue': 'Monthly Revenue',
    'admin.pendingApprovals': 'Pending Approvals',
    'admin.overview': 'Overview',
    'admin.clinics': 'Clinics',
    'admin.patients': 'Patients',
    'admin.transactions': 'Transactions',
    'admin.reports': 'Reports',
    'admin.settings': 'Settings',
    'admin.approvals': 'Approvals',
    'admin.recentClinics': 'Recent Clinics',
    'admin.recentBookings': 'Recent Bookings',
    'admin.noDataAvailable': 'No data available',
    'admin.viewDetails': 'View Details',
    'admin.approve': 'Approve',
    'admin.reject': 'Reject',
    'admin.messaging': 'Messaging',
    'admin.crm': 'CRM',
    'admin.campaigns': 'Campaigns',
    'admin.notifications': 'Notifications',
    'admin.integrations': 'Integrations',
    'admin.security': 'Security',
    'admin.activity': 'Activity',
    'admin.cms': 'CMS',
    'admin.languageSettings': 'Language Settings',
    
    // Document Review
    'document.approve': 'Approve Document',
    'document.reject': 'Reject Document',
    'document.view': 'View Document',
    'document.download': 'Download',
    'document.details': 'Document Details',
    'document.fileName': 'File Name',
    'document.fileSize': 'File Size',
    'document.uploadDate': 'Upload Date',
    'document.clinicInfo': 'Clinic Information',
    'document.documentInfo': 'Document Information',
    'document.documentType': 'Document Type',
    'document.type': 'Type',
    'document.verificationStatus': 'Verification Status',
    'document.clinic': 'Clinic',
    'document.location': 'Location',
    'document.openDocument': 'Open Document',
    'document.approved': 'Document Approved',
    'document.rejected': 'Document Rejected',
    'document.pending': 'Pending Approval',
    'document.confirmApproval': 'document? Are you sure you want to approve it?',
    'document.confirmRejection': 'document? Are you sure you want to reject it? This action cannot be undone.',
    'document.approvalNotes': 'Review notes (optional)',
    'document.rejectionReason': 'Rejection reason (recommended)',
    'document.confirmApprovalAction': 'Confirm Approval',
    'document.confirmRejectionAction': 'Confirm Rejection',
    'document.approving': 'Approving...',
    'document.rejecting': 'Rejecting...',
    
    // Treatment Approval
    'treatment.approve': 'Approve Treatment',
    'treatment.reject': 'Reject Treatment',
    'treatment.viewDetails': 'View Details',
    'treatment.approved': 'Treatment Approved',
    'treatment.rejected': 'Treatment Rejected',
    'treatment.confirmApproval': 'treatment? Are you sure you want to approve it? It will become visible to patients.',
    'treatment.confirmRejection': 'treatment? Please specify the reason for rejection:',
    'treatment.approvalNotes': 'Approval notes (optional)',
    'treatment.rejectionReason': 'Rejection reason (required)',
    
    // Messaging
    'messaging.conversations': 'Conversations',
    'messaging.newMessage': 'New Message',
    'messaging.typeMessage': 'Type your message...',
    'messaging.send': 'Send',
    'messaging.searchConversations': 'Search conversations...',
    'messaging.noConversations': 'No conversations yet',
    'messaging.selectConversation': 'Select a conversation',
    'messaging.attachFile': 'Attach File',
    'messaging.attachImage': 'Attach Image',
    'messaging.priority': 'Priority',
    'messaging.status': 'Status',
    'messaging.tags': 'Tags',
    'messaging.filters': 'Filters',
    'messaging.clearFilters': 'Clear Filters',
    'messaging.assignTo': 'Assign To',
    'messaging.unassigned': 'Unassigned',
    'messaging.markAsRead': 'Mark as Read',
    'messaging.markAsUnread': 'Mark as Unread',
    'messaging.archive': 'Archive',
    'messaging.delete': 'Delete',
    'messaging.typing': 'typing...',
    'messaging.justNow': 'Just now',
    'messaging.hoursAgo': 'hours ago',
    'messaging.daysAgo': 'days ago',
    'messaging.download': 'Download',
    'messaging.fileSize': 'File Size',
    'messaging.filtersActive': 'Filters active',
    
    // Priorities
    'priority.low': 'Low',
    'priority.normal': 'Normal',
    'priority.high': 'High',
    'priority.urgent': 'Urgent',
    
    // Status
    'status.pending': 'Pending',
    'status.approved': 'Approved',
    'status.active': 'Active',
    'status.completed': 'Completed',
    'status.resolved': 'Resolved',
    'status.closed': 'Closed',
    'status.all': 'All',
    
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.close': 'Close',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submit': 'Submit',
    'common.confirm': 'Confirm',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.clear': 'Clear',
    'common.apply': 'Apply',
    'common.reset': 'Reset',
    'common.back': 'Back',
    'common.forward': 'Forward',
    'common.refresh': 'Refresh',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.select': 'Select',
    'common.selectAll': 'Select All',
    'common.deselectAll': 'Deselect All',
    'common.add': 'Add',
    
    // Footer
    'footer.popularTreatments': 'Popular Treatments',
    'footer.topDestinations': 'Top Destinations',
    'footer.forPatients': 'For Patients',
    'footer.forClinics': 'For Clinics',
    'footer.trustTitle': 'Why Choose JAW BREAKER?',
    'footer.trustSubtitle': 'Your trusted partner in medical tourism',
    'footer.newsletter': 'Stay Updated',
    'footer.newsletterDesc': 'Get the latest deals, treatment guides, and health tourism insights delivered to your inbox.',
    'footer.subscribe': 'Subscribe',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.termsOfService': 'Terms of Service',
    'footer.cookiePolicy': 'Cookie Policy',
    'footer.medicalDisclaimer': 'Medical Disclaimer',

    // Support page translations
    'support.title': 'Support Center',
    'support.subtitle': 'We\'re here to help you every step of the way',
    'support.phoneSupport': 'Phone Support',
    'support.phoneDescription': 'Speak directly with our medical coordinators',
    'support.emailSupport': 'Email Support',
    'support.emailDescription': 'Get detailed answers to your questions',
    'support.liveChat': 'Live Chat',
    'support.chatDescription': 'Instant help from our support team',
    'support.chatWidget': 'Chat widget on every page',
    'support.available247': '24/7 Available',
    'support.responseTime': 'Response within 2 hours',
    'support.emergencySupport': 'Emergency Support',
    'support.emergencyDescription': 'If you\'re currently traveling and need immediate assistance',
    'support.emergencyAvailability': 'Available 24/7 for medical emergencies and urgent travel assistance',
    'support.faqTitle': 'Frequently Asked Questions',
    'support.faq1Question': 'How do I book a treatment?',
    'support.faq1Answer': 'Simply browse our treatments, select your preferred clinic, and click "Book Now". Our coordinators will guide you through the process.',
    'support.faq2Question': 'What\'s included in the price?',
    'support.faq2Answer': 'All packages include medical fees, accommodation, airport transfers, and a dedicated coordinator. Additional services are clearly marked.',
    'support.faq3Question': 'Is my booking protected?',
    'support.faq3Answer': 'Yes, all bookings are protected by our guarantee. We offer full refund protection and quality assurance.',
    'support.faq4Question': 'What languages do you support?',
    'support.faq4Answer': 'We provide support in English, Turkish, Russian, Arabic, German, and French. Our clinics offer multilingual staff.',
    'support.officesTitle': 'Our Offices',
    'support.usa': 'United States',
    'support.turkey': 'Turkey'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [isAdmin, setIsAdmin] = useState<boolean>(false);

  useEffect(() => {
    // Admin kontrolünü localStorage'dan kontrol et
    const userRole = localStorage.getItem('user-role');
    const adminStatus = userRole === 'admin';
    setIsAdmin(adminStatus);
  }, []);

  const t = (key: string): string => {
    const currentTranslations = translations['en'];
    if (!currentTranslations) return key;
    return currentTranslations[key as keyof typeof currentTranslations] || key;
  };

  return (
    <LanguageContext.Provider value={{ 
      t, 
      isAdmin,
      setIsAdmin
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
