// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pyacmqqtlhtexsooirhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5YWNtcXF0bGh0ZXhzb29pcmhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMDI5OTYsImV4cCI6MjA2Njc3ODk5Nn0.c1z5zgaaDLpKJZm2XBdLgBa6KwIJOE-sVi4_zFBz748";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);